# Generated by Django 5.2.3 on 2025-07-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedvideo",
            name="name",
            field=models.CharField(default="first", max_length=100),
        ),
    ]
